blueprints/auth.py
from flask import Blueprint, jsonify, request
from sqlalchemy.exc import IntegrityError
from forms import SignUpForm, LoginForm
from models import db, User
from flask_login import login_user, logout_user, current_user
from flask_jwt_extended import (
    create_access_token,
    get_current_user,
    jwt_required,
)

auth = Blueprint('auth', __name__)


@auth.post('/signup')
def signup():
    """Handle user sign up and """
    data = request.get_json()
    form = SignUpForm(data=data)

    if form.validate_on_submit():
        try:
            user = User.signup(
                email=form.data["email"],
                name=form.data["name"],
                password=form.data["password"],
            )
            db.session.commit()
            access_token = create_access_token(identity=user.id)
            return jsonify(token=access_token), 201

        except IntegrityError:
            return (jsonify(status="error", message="Email already taken")), 409

    else:
        return (jsonify(status="error", message="Invalid credentials")), 500


@auth.post('/login')
def login():
    """Handle user login and redirect to homepage on success."""
    data = request.get_json()
    form = LoginForm(data=data)

    if form.validate_on_submit():
        user = User.authenticate(
            form.email.data,
            form.password.data
        )

        if user:
            access_token = create_access_token(identity=user.id)
            return jsonify(token=access_token), 201
        else:
            return (jsonify(status="error", message="Invalid credentials"))
    else:
        return jsonify(errors=form.errors), 400


@auth.get('/users/<int:id>')
@jwt_required()
def user_profile(id):
    """Gets all user information associated with user id"""
    try:
        user = User.query.get_or_404(id)
        return jsonify(user=user.serialize())
    except Exception as e:
        return jsonify(errors=e), 404

blueprints/main.py
from flask import Blueprint,render_template, flash, g
from flask_jwt_extended import (
    jwt_required,
)

main = Blueprint('main', __name__)

@main.route('/')
@jwt_required
def index():
    if not g.user.plant_plots:
        flash(f"You don't have any seeds, go buy some!")
    return render_template('garden.html')

templates/components/alerts.html
<div class="alert-container">
  {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alertbox alert-{{ category }}">
      <p>{{ message }}</p>
    </div>
  {% endfor %}
</div>

templates/components/nav-bar.html
<div id="navbar">
  <a href="{{ url_for('main.index') }}" class="navbar-item">Home</a>
  {% if not current_user.is_authenticated %}
    <a href="{{ url_for('auth.login') }}" class="navbar-item">Login</a>
    <a href="{{ url_for('auth.signup') }}" class="navbar-item">Sign Up</a>
  {% endif %}
  {% if current_user.is_authenticated %}
    <a data-bs-toggle="modal" data-bs-target="#open-shop" class="navbar-item">Shop</a>
    <a href="{{ url_for('auth.logout') }}" class="navbar-item">Logout</a>
  {% endif %}
</div>

templates/components/shop-modal.html
<!-- Modal -->
<div class="modal fade" id="open-shop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-wrapper">
    <div class="modal-dialog">
      <div class="modal-content border-wood-lg">
        <div class="modal-header">
          <h1 class="modal-title border-card">Shop</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body shop">
          <p>Coins: {{current_user.coins}}</p>
          <div>
            {% for seed in g.seeds %}
            <div class="shop-item">
              <div class="item-details">
                <img src="/static/seeds/{{seed.seed_sprite}}" alt="">
                <span>{{seed.name | capitalize}} Seeds</span>
              </div>
              <div class="buy-details">
                <span class="coin-symbol">{{seed.buy_price}}</span>
                <form method="POST">
                  <button formaction="/buy/{{seed.name}}" type="submit" class="button">Buy Now</button>
                </form>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>